In [1]:
import numpy as np

In [15]:
def pagerank(M: np.ndarray, beta: float, epsilon: float) -> np.ndarray:
    n = M.shape[1]
    v = 1/n * np.ones(n)
    A = M* beta + (1-beta)/n * np.ones((n,n))
    v_new = A @ v
    while np.sum(np.abs(v - v_new)) > epsilon:
        v = v_new
        v_new = A @ v
    return v_new

In [14]:
n = 5
M_ones = np.ones((n, n))
v_ones = np.ones(n)
result = M_ones @ v_ones
print(result)

[5. 5. 5. 5. 5.]


In [ ]:
def gen_M(num_vertices) -> np.ndarray:
    M = (np.ones((num_vertices, num_vertices)) - np.eye(num_vertices) )/ (num_vertices-1)
    return M

In [18]:
beta = 0.9
epsilon = 1e-3
M = np.array([[0, 0, 1/3, 0, 0],
              [0.5, 0, 0, 0, 0],
              [0.5, 0, 0, 0, 0],
              [0, 1/3, 2/3, 0, 0],
              [0, 1/3, 0, 1, 1]])

v =pagerank(M, beta, epsilon)
print(v)
print(np.sum(v))

[0.00293527 0.00327664 0.00327664 0.00492157 0.08170279]
0.09611291270258236


In [19]:
M_4 = gen_M(4)
M_6 = gen_M(6)

beta = 4/5
epsilon = 1/12

# b)
print(pagerank(M_4, beta, epsilon))
print(pagerank(M_6, beta, epsilon))

[0.25 0.25 0.25 0.25]
[0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
