In [1]:
import numpy as np
import random

In [2]:
print(random.randint(0,2))

0


In [ ]:

def generating_data(m,q,df, N):
    '''
    Exercise 5

    Input:
    - m: number of columns
    - q: number of non zero parameters
    - df: difference factor
    - N: rows

    Output:
    - ds: matrix as input for computation of signature matrix
    '''
    ds = np.zeros([N,m])
    random_int =[]
    for i in range(q):
        pos = random.randint(0,N-1)
        while pos in random_int:
            pos = random.randint(0,N-1)
        ds[pos,0]= 1
        random_int.append(pos)

    for column in range(1,m):
        current_positions = np.where(ds[:,column-1] == 1)[0]

        # Step 2: Determine the number of positions to replace
        replace_number =  int(df * q)

        # Step 3: Randomly select positions to replace
        replace_positions = np.random.choice(current_positions,  replace_number,replace=False)
        for i in replace_positions:
            ds[i,column] = 1
        # Step 4: Generate new unique positions
        available_positions = np.where(ds[:,column-1] == 0)[0]
        new_positions = np.random.choice(available_positions, q - replace_number,replace=False)
        for i in new_positions:
            ds[i,column] = 1

    return ds


In [4]:
print(generating_data(10, 10, 0.2, 100))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0.

In [5]:
matrix =generating_data(100,20000,0.02,10**6)
print(matrix)
# everything above that cant handle my laptop



[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [6]:
dumb = np.array([[0., 0., 0., 0., 0.],
 [1. ,0., 0., 0., 0.],
 [1., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0.],
 [1., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0.]])

for column in range(1,5):
        current_positions = np.where(dumb[:,column-1] == 1)[0]

        # Step 2: Determine the number of positions to replace
        replace_number =  int(1)

        # Step 3: Randomly select positions to replace
        replace_positions = np.random.choice(current_positions,  replace_number,replace=False)
        for i in replace_positions:
            dumb[i,column] = 1
        # Step 4: Generate new unique positions
        available_positions = np.where(dumb[:,column-1] == 0)[0]
        new_positions = np.random.choice(available_positions, 2,replace=False)

        for i in new_positions:
            dumb[i,column] = 1

print(dumb)

[[0. 0. 0. 1. 1.]
 [1. 0. 1. 0. 1.]
 [1. 0. 1. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 1. 1. 0. 1.]
 [0. 1. 0. 1. 0.]]


In [7]:
x = np.arange(1, 101).reshape(20, 5)
print(x)
print(x[:,0])
for col in x.T:
    print(col)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]
 [ 21  22  23  24  25]
 [ 26  27  28  29  30]
 [ 31  32  33  34  35]
 [ 36  37  38  39  40]
 [ 41  42  43  44  45]
 [ 46  47  48  49  50]
 [ 51  52  53  54  55]
 [ 56  57  58  59  60]
 [ 61  62  63  64  65]
 [ 66  67  68  69  70]
 [ 71  72  73  74  75]
 [ 76  77  78  79  80]
 [ 81  82  83  84  85]
 [ 86  87  88  89  90]
 [ 91  92  93  94  95]
 [ 96  97  98  99 100]]
[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]
[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]
[ 2  7 12 17 22 27 32 37 42 47 52 57 62 67 72 77 82 87 92 97]
[ 3  8 13 18 23 28 33 38 43 48 53 58 63 68 73 78 83 88 93 98]
[ 4  9 14 19 24 29 34 39 44 49 54 59 64 69 74 79 84 89 94 99]
[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [78]:
def generate_hash_functions(num_hash_funcs):
    p = 2**31 - 1
    hash_funcs = [(random.randint(0, 10**12), random.randint(0, 10**12), p) for _ in range(num_hash_funcs)]
    return hash_funcs

def approx_permutation(num_rows, hash_params):
    col = np.arange(num_rows)
    a, b, p = hash_params
    hash = ((a*col + b) % p) % num_rows
    return hash

def minHashing(col, hashed_col):
    min_hash = None
    for idx, hash_elem in enumerate(hashed_col):
        smaller_val_cond =  (min_hash == None or min_hash > hash_elem )
        if smaller_val_cond and col[idx] == 1:
            min_hash = hash_elem
    return min_hash


def minHash_signatures(input_data, hash_funcs):
    num_hash_funcs = len(hash_funcs)
    num_cols = input_data.shape[1]
    num_rows = input_data.shape[0]
    signature = np.empty((num_hash_funcs, num_cols))
    for idx_row, hash_params in enumerate(hash_funcs):
            hash_col = approx_permutation(num_rows, hash_params)
            for idx_col, col in enumerate(input_data.T):
                min_hash = minHashing(col, hash_col)
                signature[idx_row, idx_col] = min_hash
    return signature

In [93]:
def create_sig_matrix_routine(num_cols, num_rows, q, df, num_hash_funcs, ):
    hash_funcs = generate_hash_functions(num_hash_funcs)
    data = generating_data(num_cols, q, df, num_rows)
    sig_matrix = minHash_signatures(data, hash_funcs)
    return sig_matrix

test = create_sig_matrix_routine(10, 100,  2, 0.1, 5)
print(test)

[[19. 63. 22. 15. 33.  8. 53. 73.  3. 59.]
 [32. 28. 19. 21. 50. 11. 77.  3. 21. 38.]
 [24. 64. 48.  8. 30. 41. 19.  8. 41. 48.]
 [ 5. 35. 43.  3. 22. 56.  8. 19. 36. 82.]
 [14. 64. 25. 14.  5. 52. 27. 63. 22. 11.]]


In [ ]:
hash_funcs = generate_hash_functions(2)
print(hash_funcs)
elem = 0

test_data = generating_data(10, 9, 0.2, 20)
print(test_data)
test_col = test_data[:, 0]
print(test_col)
hashed_col = approx_permutation(10, hash_funcs[0])
print(hashed_col)
test_hash = minHashing(test_col, hashed_col)
print(test_hash)

test_sig = minHash_signatures(test_data, hash_funcs)
print(test_sig)

[(937008289145, 755886307574, 2147483647), (501866831459, 41158737821, 2147483647)]
[[1. 0. 1. 1. 0. 0. 0. 1. 0. 1.]
 [0. 1. 0. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 0. 0. 1. 1. 0. 1.]
 [0. 0. 1. 0. 1. 1. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 0. 1. 1. 0.]
 [0. 1. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 1. 1. 0. 1. 0. 1. 0. 0. 1.]
 [1. 0. 1. 0. 1. 0. 0. 0. 1. 0.]
 [1. 1. 0. 1. 0. 1. 0. 0. 1. 1.]
 [1. 0. 0. 1. 0. 1. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 0. 1. 1. 0. 1. 0. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 1. 0. 1.]
 [0. 0. 1. 0. 1. 0. 1. 0. 1. 0.]]
[1. 0. 0. 1. 0. 1. 0. 0. 1. 1. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
[7 3 6 9 5 8 1 7 0 3]
0
[[0. 1. 0. 1. 0. 3. 1. 3. 0. 5.]
 [7. 0. 6. 0. 6. 0. 6. 7. 0. 7.]]


In [ ]:
def compute_signature_matrix(num_hash_funcs, N, input_data):

    hash_funcs = generate_hash_functions(num_hash_funcs)
    num_cols = input_data.shape[1]
    # Initialize the signature matrix
    sig_matrix = np.zeros((num_hash_funcs, num_cols),dtype=int)

    # Compute MinHash signatures for each column
    for col_idx in  range(num_cols):
        signature = minhash_signatures(input_data[:,col_idx], hash_funcs,N)
        print(signature)
        for row_idx in range(num_hash_funcs):
            sig_matrix[row_idx,col_idx] = signature[row_idx]

    return sig_matrix

#compute_signature_matrix(7,10**8,dumb)

In [17]:
test = generating_data(10, 9, 0.2, 20)
print(test)

[[0. 1. 0. 1. 0. 1. 0. 1. 1. 0.]
 [0. 0. 1. 0. 1. 0. 0. 1. 0. 0.]
 [1. 0. 1. 0. 0. 1. 1. 0. 1. 0.]
 [0. 1. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 0. 0. 1. 1. 0. 1.]
 [0. 1. 0. 0. 1. 0. 1. 0. 1. 0.]
 [1. 1. 0. 1. 0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1. 0. 0. 1. 0.]
 [1. 0. 1. 1. 0. 0. 1. 0. 1. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0. 1. 0. 1.]
 [0. 1. 0. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 0. 1. 0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 0. 1. 0. 1. 0. 1. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 0. 1.]
 [0. 1. 0. 1. 1. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 1. 0. 1. 0. 0. 1.]
 [1. 0. 1. 0. 1. 0. 0. 1. 0. 1.]]
